version: "3.8"

services:
  oracle:
    image: gvenzl/oracle-xe
    container_name: oracle
    ports:
      - "1522:1521"
    environment:
      ORACLE_PASSWORD: test123
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'select 1 from dual;' | sqlplus -s system/test123@localhost/XE"]
      interval: 10s
      timeout: 5s
      retries: 10
      
  tomcat:
    build:
      context: .
    container_name: tomcat
    ports:
      - "8080:8080"
    depends_on:
      oracle:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - tomcat
      
    

